version: "3"

services:
  database:
    image: mysql:5.7
    restart: on-failure
    volumes:
      - ./database/mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db_root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_usr
      MYSQL_PASSWORD: db_pwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    expose:
      - "80"
    ports:
      - "3307:80"
    environment:
      PMA_HOST: database
      PMA_USER: db_usr
      PMA_PASSWORD: db_pwd
