import os

CHATWORK_API_TOKEN = os.environ.get('CHATWORK_API_TOKEN')
CHATWORK_CLIENT_ID = os.environ.get('CHATWORK_CLIENT_ID')
CHATWORK_CLIENT_SECRET = os.environ.get('CHATWORK_CLIENT_SECRET')
CHATWORK_SCOPE = os.environ.get('CHATWORK_SCOPE')
CHATWORK_REDIRECT_URI = os.environ.get('CHATWORK_REDIRECT_URI')
