import os

GITHUB_CLIENT_ID = os.environ.get('GITHUB_CLIENT_ID')
GITHUB_CLIENT_SECRET = os.environ.get('GITHUB_CLIENT_SECRET')
GITHUB_SCOPE = os.environ.get('GITHUB_SCOPE')
GITHUB_REDIRECT_URI = os.environ.get('GITHUB_REDIRECT_URI')
