class Constants(object):
    # User
    USER_NAME_MIN_LENGTH = 3
    USER_NAME_MAX_LENGTH = 50
    USER_PASSWORD_MIN_LENGTH = 6
    USER_PASSWORD_MAX_LENGTH = 30

    # Role
    ROLE_ADMIN_CODE = 1
    ROLE_ADMIN_NAME = 'Admin'
    ROLE_MEMBER_CODE = 2
    ROLE_MEMBER_NAME = 'Member'

    # Group
    GROUP_ADMIN_CODE = 1
    GROUP_ADMIN_NAME = 'Admin'
    GROUP_OPERATOR_CODE = 2
    GROUP_OPERATOR_NAME = 'Operator'
